[build]
  base = "EMTBApp"
  publish = "ProMedixEMS-main/dist"
  command = "cd ProMedixEMS-main && npm install --legacy-peer-deps && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200