[build]
  base = "EMTBApp"
  publish = "ProMedixEMS-main/dist"
  command = "cd ProMedixEMS-main && npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_API_URL = "https://emeritarig-production.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200